plugins {
    id "java"
    id "org.jetbrains.kotlin.jvm" version "2.0.0"
    id 'com.gradleup.shadow' version '8.3.0' 
}

group = "com.ytlaw80.fplplugin"
version = "1.0.0"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT"
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = "21"
    }
}

tasks.withType(Jar).configureEach {
    archiveBaseName.set("FPL_Plugin")
}

shadowJar {
    // 생성될 JAR 파일의 이름 설정
    archiveBaseName.set('FPLPlugin')
    archiveClassifier.set('')
    archiveVersion.set('1.0.0')

    // 실행 가능한 JAR를 위한 메인 클래스 지정
    manifest {
        attributes 'Main-Class': 'com.example.fplplugin'
    }
}